function AIAAWG100cpd0 = importMatrix(filename, dataLines)
%IMPORTFILE Import data from a text file
%  AIAAWG100CPD0 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  AIAAWG100CPD0 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  AIAAWG100cpd0 = importfile("/mnt/RRG2_Backup/Andrew_backup/aerobreakup/AIAA_WG_shot3/2D/100cpd_clean/processing/data/AIAAWG_100cpd_0.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Apr-2025 10:19:32

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "CellType", "Density", "Grho", "VOF"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "CellType", "TrimNonNumeric", true);
opts = setvaropts(opts, "CellType", "ThousandsSeparator", ",");

% Import the data
AIAAWG100cpd0 = readtable(filename, opts);

%% Convert to output type
AIAAWG100cpd0 = table2array(AIAAWG100cpd0);
end