function schlierendata0 = importschlierenvars(filename, dataLines)
%IMPORTFILE Import data from a text file
%  SCHLIERENDATA0 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  SCHLIERENDATA0 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  schlierendata0 = importfile("/mnt/RRG2_Backup/Andrew_backup/aerobreakup/AIAAWG_shot3/2D/500cpd_perturbed_vs_unperturbed/500cpd_PLICNET_perturbed_7-7-2025/schlieren_processing/data/schlieren_data_0.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Jul-2025 11:29:12

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "CellType", "Density", "VOF"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "CellType", "TrimNonNumeric", true);
opts = setvaropts(opts, "CellType", "ThousandsSeparator", ",");

% Import the data
schlierendata0 = readtable(filename, opts);

%% Convert to output type
schlierendata0 = table2array(schlierendata0);
end